/* Automatically @generated by tree-sitter */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 12
#define LARGE_STATE_COUNT 5
#define SYMBOL_COUNT 25
#define ALIAS_COUNT 0
#define TOKEN_COUNT 19
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 3
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 1
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  anon_sym_LF = 1,
  sym_comment = 2,
  anon_sym_unmap = 3,
  anon_sym_eval = 4,
  anon_sym_default_linemode = 5,
  anon_sym_set = 6,
  anon_sym_setlocal = 7,
  anon_sym_map = 8,
  anon_sym_cmap = 9,
  anon_sym_pmap = 10,
  anon_sym_tmap = 11,
  anon_sym_copymap = 12,
  anon_sym_copycmap = 13,
  anon_sym_copypmap = 14,
  anon_sym_copytmap = 15,
  anon_sym_alias = 16,
  sym_argument_key = 17,
  sym_argument_value = 18,
  sym_source_file = 19,
  sym__line = 20,
  sym__command_lines = 21,
  sym_single_arg_command = 22,
  sym_double_arg_command = 23,
  aux_sym_source_file_repeat1 = 24,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_LF] = "\n",
  [sym_comment] = "comment",
  [anon_sym_unmap] = "keyword",
  [anon_sym_eval] = "keyword",
  [anon_sym_default_linemode] = "keyword",
  [anon_sym_set] = "keyword",
  [anon_sym_setlocal] = "keyword",
  [anon_sym_map] = "keyword",
  [anon_sym_cmap] = "keyword",
  [anon_sym_pmap] = "keyword",
  [anon_sym_tmap] = "keyword",
  [anon_sym_copymap] = "keyword",
  [anon_sym_copycmap] = "keyword",
  [anon_sym_copypmap] = "keyword",
  [anon_sym_copytmap] = "keyword",
  [anon_sym_alias] = "keyword",
  [sym_argument_key] = "argument_key",
  [sym_argument_value] = "argument_value",
  [sym_source_file] = "source_file",
  [sym__line] = "_line",
  [sym__command_lines] = "_command_lines",
  [sym_single_arg_command] = "single_arg_command",
  [sym_double_arg_command] = "double_arg_command",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_LF] = anon_sym_LF,
  [sym_comment] = sym_comment,
  [anon_sym_unmap] = anon_sym_unmap,
  [anon_sym_eval] = anon_sym_unmap,
  [anon_sym_default_linemode] = anon_sym_unmap,
  [anon_sym_set] = anon_sym_unmap,
  [anon_sym_setlocal] = anon_sym_unmap,
  [anon_sym_map] = anon_sym_unmap,
  [anon_sym_cmap] = anon_sym_unmap,
  [anon_sym_pmap] = anon_sym_unmap,
  [anon_sym_tmap] = anon_sym_unmap,
  [anon_sym_copymap] = anon_sym_unmap,
  [anon_sym_copycmap] = anon_sym_unmap,
  [anon_sym_copypmap] = anon_sym_unmap,
  [anon_sym_copytmap] = anon_sym_unmap,
  [anon_sym_alias] = anon_sym_unmap,
  [sym_argument_key] = sym_argument_key,
  [sym_argument_value] = sym_argument_value,
  [sym_source_file] = sym_source_file,
  [sym__line] = sym__line,
  [sym__command_lines] = sym__command_lines,
  [sym_single_arg_command] = sym_single_arg_command,
  [sym_double_arg_command] = sym_double_arg_command,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_LF] = {
    .visible = true,
    .named = false,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_unmap] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_eval] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_default_linemode] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_set] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_setlocal] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_map] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_cmap] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_pmap] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_tmap] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_copymap] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_copycmap] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_copypmap] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_copytmap] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_alias] = {
    .visible = true,
    .named = true,
  },
  [sym_argument_key] = {
    .visible = true,
    .named = true,
  },
  [sym_argument_value] = {
    .visible = true,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym__line] = {
    .visible = false,
    .named = true,
  },
  [sym__command_lines] = {
    .visible = false,
    .named = true,
  },
  [sym_single_arg_command] = {
    .visible = true,
    .named = true,
  },
  [sym_double_arg_command] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(60);
      ADVANCE_MAP(
        '\n', 61,
        '#', 62,
        'a', 26,
        'c', 32,
        'd', 19,
        'e', 57,
        'm', 6,
        'p', 33,
        's', 20,
        't', 34,
        'u', 40,
      );
      if (lookahead == '\t' ||
          lookahead == ' ') SKIP(0);
      END_STATE();
    case 1:
      if (lookahead == '\n') ADVANCE(61);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(78);
      if (lookahead != 0) ADVANCE(79);
      END_STATE();
    case 2:
      if (lookahead == '_') ADVANCE(29);
      END_STATE();
    case 3:
      if (lookahead == 'a') ADVANCE(53);
      END_STATE();
    case 4:
      if (lookahead == 'a') ADVANCE(56);
      END_STATE();
    case 5:
      if (lookahead == 'a') ADVANCE(27);
      END_STATE();
    case 6:
      if (lookahead == 'a') ADVANCE(44);
      END_STATE();
    case 7:
      if (lookahead == 'a') ADVANCE(45);
      END_STATE();
    case 8:
      if (lookahead == 'a') ADVANCE(28);
      END_STATE();
    case 9:
      if (lookahead == 'a') ADVANCE(46);
      END_STATE();
    case 10:
      if (lookahead == 'a') ADVANCE(47);
      END_STATE();
    case 11:
      if (lookahead == 'a') ADVANCE(48);
      END_STATE();
    case 12:
      if (lookahead == 'a') ADVANCE(49);
      END_STATE();
    case 13:
      if (lookahead == 'a') ADVANCE(50);
      END_STATE();
    case 14:
      if (lookahead == 'a') ADVANCE(51);
      END_STATE();
    case 15:
      if (lookahead == 'a') ADVANCE(52);
      END_STATE();
    case 16:
      if (lookahead == 'c') ADVANCE(8);
      END_STATE();
    case 17:
      if (lookahead == 'c') ADVANCE(36);
      if (lookahead == 'm') ADVANCE(12);
      if (lookahead == 'p') ADVANCE(37);
      if (lookahead == 't') ADVANCE(38);
      END_STATE();
    case 18:
      if (lookahead == 'd') ADVANCE(21);
      END_STATE();
    case 19:
      if (lookahead == 'e') ADVANCE(23);
      END_STATE();
    case 20:
      if (lookahead == 'e') ADVANCE(54);
      END_STATE();
    case 21:
      if (lookahead == 'e') ADVANCE(65);
      END_STATE();
    case 22:
      if (lookahead == 'e') ADVANCE(31);
      END_STATE();
    case 23:
      if (lookahead == 'f') ADVANCE(4);
      END_STATE();
    case 24:
      if (lookahead == 'i') ADVANCE(39);
      END_STATE();
    case 25:
      if (lookahead == 'i') ADVANCE(3);
      END_STATE();
    case 26:
      if (lookahead == 'l') ADVANCE(25);
      END_STATE();
    case 27:
      if (lookahead == 'l') ADVANCE(64);
      END_STATE();
    case 28:
      if (lookahead == 'l') ADVANCE(67);
      END_STATE();
    case 29:
      if (lookahead == 'l') ADVANCE(24);
      END_STATE();
    case 30:
      if (lookahead == 'l') ADVANCE(55);
      END_STATE();
    case 31:
      if (lookahead == 'm') ADVANCE(42);
      END_STATE();
    case 32:
      if (lookahead == 'm') ADVANCE(7);
      if (lookahead == 'o') ADVANCE(43);
      END_STATE();
    case 33:
      if (lookahead == 'm') ADVANCE(9);
      END_STATE();
    case 34:
      if (lookahead == 'm') ADVANCE(10);
      END_STATE();
    case 35:
      if (lookahead == 'm') ADVANCE(11);
      END_STATE();
    case 36:
      if (lookahead == 'm') ADVANCE(13);
      END_STATE();
    case 37:
      if (lookahead == 'm') ADVANCE(14);
      END_STATE();
    case 38:
      if (lookahead == 'm') ADVANCE(15);
      END_STATE();
    case 39:
      if (lookahead == 'n') ADVANCE(22);
      END_STATE();
    case 40:
      if (lookahead == 'n') ADVANCE(35);
      END_STATE();
    case 41:
      if (lookahead == 'o') ADVANCE(16);
      END_STATE();
    case 42:
      if (lookahead == 'o') ADVANCE(18);
      END_STATE();
    case 43:
      if (lookahead == 'p') ADVANCE(58);
      END_STATE();
    case 44:
      if (lookahead == 'p') ADVANCE(68);
      END_STATE();
    case 45:
      if (lookahead == 'p') ADVANCE(69);
      END_STATE();
    case 46:
      if (lookahead == 'p') ADVANCE(70);
      END_STATE();
    case 47:
      if (lookahead == 'p') ADVANCE(71);
      END_STATE();
    case 48:
      if (lookahead == 'p') ADVANCE(63);
      END_STATE();
    case 49:
      if (lookahead == 'p') ADVANCE(72);
      END_STATE();
    case 50:
      if (lookahead == 'p') ADVANCE(73);
      END_STATE();
    case 51:
      if (lookahead == 'p') ADVANCE(74);
      END_STATE();
    case 52:
      if (lookahead == 'p') ADVANCE(75);
      END_STATE();
    case 53:
      if (lookahead == 's') ADVANCE(76);
      END_STATE();
    case 54:
      if (lookahead == 't') ADVANCE(66);
      END_STATE();
    case 55:
      if (lookahead == 't') ADVANCE(2);
      END_STATE();
    case 56:
      if (lookahead == 'u') ADVANCE(30);
      END_STATE();
    case 57:
      if (lookahead == 'v') ADVANCE(5);
      END_STATE();
    case 58:
      if (lookahead == 'y') ADVANCE(17);
      END_STATE();
    case 59:
      if (lookahead == '\t' ||
          lookahead == ' ') SKIP(59);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead)) ADVANCE(77);
      END_STATE();
    case 60:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 61:
      ACCEPT_TOKEN(anon_sym_LF);
      END_STATE();
    case 62:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(62);
      END_STATE();
    case 63:
      ACCEPT_TOKEN(anon_sym_unmap);
      END_STATE();
    case 64:
      ACCEPT_TOKEN(anon_sym_eval);
      END_STATE();
    case 65:
      ACCEPT_TOKEN(anon_sym_default_linemode);
      END_STATE();
    case 66:
      ACCEPT_TOKEN(anon_sym_set);
      if (lookahead == 'l') ADVANCE(41);
      END_STATE();
    case 67:
      ACCEPT_TOKEN(anon_sym_setlocal);
      END_STATE();
    case 68:
      ACCEPT_TOKEN(anon_sym_map);
      END_STATE();
    case 69:
      ACCEPT_TOKEN(anon_sym_cmap);
      END_STATE();
    case 70:
      ACCEPT_TOKEN(anon_sym_pmap);
      END_STATE();
    case 71:
      ACCEPT_TOKEN(anon_sym_tmap);
      END_STATE();
    case 72:
      ACCEPT_TOKEN(anon_sym_copymap);
      END_STATE();
    case 73:
      ACCEPT_TOKEN(anon_sym_copycmap);
      END_STATE();
    case 74:
      ACCEPT_TOKEN(anon_sym_copypmap);
      END_STATE();
    case 75:
      ACCEPT_TOKEN(anon_sym_copytmap);
      END_STATE();
    case 76:
      ACCEPT_TOKEN(anon_sym_alias);
      END_STATE();
    case 77:
      ACCEPT_TOKEN(sym_argument_key);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ') ADVANCE(77);
      END_STATE();
    case 78:
      ACCEPT_TOKEN(sym_argument_value);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(78);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n') ADVANCE(79);
      END_STATE();
    case 79:
      ACCEPT_TOKEN(sym_argument_value);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(79);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 0},
  [3] = {.lex_state = 0},
  [4] = {.lex_state = 0},
  [5] = {.lex_state = 1},
  [6] = {.lex_state = 1},
  [7] = {.lex_state = 59},
  [8] = {.lex_state = 0},
  [9] = {.lex_state = 0},
  [10] = {.lex_state = 0},
  [11] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_LF] = ACTIONS(1),
    [sym_comment] = ACTIONS(1),
    [anon_sym_unmap] = ACTIONS(1),
    [anon_sym_eval] = ACTIONS(1),
    [anon_sym_default_linemode] = ACTIONS(1),
    [anon_sym_set] = ACTIONS(1),
    [anon_sym_setlocal] = ACTIONS(1),
    [anon_sym_map] = ACTIONS(1),
    [anon_sym_cmap] = ACTIONS(1),
    [anon_sym_pmap] = ACTIONS(1),
    [anon_sym_tmap] = ACTIONS(1),
    [anon_sym_copymap] = ACTIONS(1),
    [anon_sym_copycmap] = ACTIONS(1),
    [anon_sym_copypmap] = ACTIONS(1),
    [anon_sym_copytmap] = ACTIONS(1),
    [anon_sym_alias] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(8),
    [sym__line] = STATE(2),
    [sym__command_lines] = STATE(2),
    [sym_single_arg_command] = STATE(9),
    [sym_double_arg_command] = STATE(9),
    [aux_sym_source_file_repeat1] = STATE(2),
    [ts_builtin_sym_end] = ACTIONS(3),
    [anon_sym_LF] = ACTIONS(5),
    [sym_comment] = ACTIONS(5),
    [anon_sym_unmap] = ACTIONS(7),
    [anon_sym_eval] = ACTIONS(7),
    [anon_sym_default_linemode] = ACTIONS(7),
    [anon_sym_set] = ACTIONS(9),
    [anon_sym_setlocal] = ACTIONS(11),
    [anon_sym_map] = ACTIONS(11),
    [anon_sym_cmap] = ACTIONS(11),
    [anon_sym_pmap] = ACTIONS(11),
    [anon_sym_tmap] = ACTIONS(11),
    [anon_sym_copymap] = ACTIONS(11),
    [anon_sym_copycmap] = ACTIONS(11),
    [anon_sym_copypmap] = ACTIONS(11),
    [anon_sym_copytmap] = ACTIONS(11),
    [anon_sym_alias] = ACTIONS(11),
  },
  [STATE(2)] = {
    [sym__line] = STATE(3),
    [sym__command_lines] = STATE(3),
    [sym_single_arg_command] = STATE(9),
    [sym_double_arg_command] = STATE(9),
    [aux_sym_source_file_repeat1] = STATE(3),
    [ts_builtin_sym_end] = ACTIONS(13),
    [anon_sym_LF] = ACTIONS(15),
    [sym_comment] = ACTIONS(15),
    [anon_sym_unmap] = ACTIONS(7),
    [anon_sym_eval] = ACTIONS(7),
    [anon_sym_default_linemode] = ACTIONS(7),
    [anon_sym_set] = ACTIONS(9),
    [anon_sym_setlocal] = ACTIONS(11),
    [anon_sym_map] = ACTIONS(11),
    [anon_sym_cmap] = ACTIONS(11),
    [anon_sym_pmap] = ACTIONS(11),
    [anon_sym_tmap] = ACTIONS(11),
    [anon_sym_copymap] = ACTIONS(11),
    [anon_sym_copycmap] = ACTIONS(11),
    [anon_sym_copypmap] = ACTIONS(11),
    [anon_sym_copytmap] = ACTIONS(11),
    [anon_sym_alias] = ACTIONS(11),
  },
  [STATE(3)] = {
    [sym__line] = STATE(3),
    [sym__command_lines] = STATE(3),
    [sym_single_arg_command] = STATE(9),
    [sym_double_arg_command] = STATE(9),
    [aux_sym_source_file_repeat1] = STATE(3),
    [ts_builtin_sym_end] = ACTIONS(17),
    [anon_sym_LF] = ACTIONS(19),
    [sym_comment] = ACTIONS(19),
    [anon_sym_unmap] = ACTIONS(22),
    [anon_sym_eval] = ACTIONS(22),
    [anon_sym_default_linemode] = ACTIONS(22),
    [anon_sym_set] = ACTIONS(25),
    [anon_sym_setlocal] = ACTIONS(28),
    [anon_sym_map] = ACTIONS(28),
    [anon_sym_cmap] = ACTIONS(28),
    [anon_sym_pmap] = ACTIONS(28),
    [anon_sym_tmap] = ACTIONS(28),
    [anon_sym_copymap] = ACTIONS(28),
    [anon_sym_copycmap] = ACTIONS(28),
    [anon_sym_copypmap] = ACTIONS(28),
    [anon_sym_copytmap] = ACTIONS(28),
    [anon_sym_alias] = ACTIONS(28),
  },
  [STATE(4)] = {
    [ts_builtin_sym_end] = ACTIONS(31),
    [anon_sym_LF] = ACTIONS(31),
    [sym_comment] = ACTIONS(31),
    [anon_sym_unmap] = ACTIONS(31),
    [anon_sym_eval] = ACTIONS(31),
    [anon_sym_default_linemode] = ACTIONS(31),
    [anon_sym_set] = ACTIONS(33),
    [anon_sym_setlocal] = ACTIONS(31),
    [anon_sym_map] = ACTIONS(31),
    [anon_sym_cmap] = ACTIONS(31),
    [anon_sym_pmap] = ACTIONS(31),
    [anon_sym_tmap] = ACTIONS(31),
    [anon_sym_copymap] = ACTIONS(31),
    [anon_sym_copycmap] = ACTIONS(31),
    [anon_sym_copypmap] = ACTIONS(31),
    [anon_sym_copytmap] = ACTIONS(31),
    [anon_sym_alias] = ACTIONS(31),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 2,
    ACTIONS(35), 1,
      anon_sym_LF,
    ACTIONS(37), 1,
      sym_argument_value,
  [7] = 2,
    ACTIONS(39), 1,
      anon_sym_LF,
    ACTIONS(41), 1,
      sym_argument_value,
  [14] = 1,
    ACTIONS(43), 1,
      sym_argument_key,
  [18] = 1,
    ACTIONS(45), 1,
      ts_builtin_sym_end,
  [22] = 1,
    ACTIONS(47), 1,
      anon_sym_LF,
  [26] = 1,
    ACTIONS(49), 1,
      anon_sym_LF,
  [30] = 1,
    ACTIONS(51), 1,
      anon_sym_LF,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(5)] = 0,
  [SMALL_STATE(6)] = 7,
  [SMALL_STATE(7)] = 14,
  [SMALL_STATE(8)] = 18,
  [SMALL_STATE(9)] = 22,
  [SMALL_STATE(10)] = 26,
  [SMALL_STATE(11)] = 30,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [9] = {.entry = {.count = 1, .reusable = false}}, SHIFT(7),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [13] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [17] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [19] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(3),
  [22] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(5),
  [25] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(7),
  [28] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(7),
  [31] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__command_lines, 2, 0, 0),
  [33] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__command_lines, 2, 0, 0),
  [35] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_single_arg_command, 1, 0, 0),
  [37] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [39] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_double_arg_command, 2, 0, 0),
  [41] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [43] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [45] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [47] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [49] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_single_arg_command, 2, 0, 0),
  [51] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_double_arg_command, 3, 0, 0),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_rangerrc(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
    .name = "rangerrc",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
